/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MyInternalFrame.java
 *
 * Created on Jun 18, 2012, 3:05:12 PM
 */
package Project;

/**
 *
 * @author josealvarado
 */
public class MyInternalFrame extends javax.swing.JInternalFrame {

    AdministrationTools AdminTools;
    
    /** Creates new form MyInternalFrame */
    public MyInternalFrame(AdministrationTools AT) {
        initComponents();
        setBounds(50, 50, 100, 100);
        setVisible(true);
        AdminTools = AT;
        this.resizable = true;
        this.closable = true;
        this.maximizable = true;
        this.iconable = true;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
