/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PlatformControlCenter.java
 *
 * Created on Jun 18, 2012, 10:18:24 AM
 */
package Project;

/**
 *
 * @author josealvarado
 */
public class PlatformControlCenter extends javax.swing.JFrame {

    AdministrationTools IFD;
    
    /** Creates new form PlatformControlCenter */
    public PlatformControlCenter() {
        initComponents();
        setBounds(50, 50, 500, 500);
        setVisible(true);
        setTitle("Platform Control Center");
    }

    void connectToServer(){
        try {
            Thread.sleep(5000);
        } catch (InterruptedException e) {
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TA = new javax.swing.JTextArea();
        TALabel = new javax.swing.JLabel();
        ServerButton = new javax.swing.JButton();
        ServerLabel = new javax.swing.JLabel();
        AdministrationToolsButton = new javax.swing.JButton();
        AdministrationToolsLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        TA.setColumns(20);
        TA.setRows(5);
        jScrollPane1.setViewportView(TA);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(80, 70, 340, 240);

        TALabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TALabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TALabel.setText("Welcome to Platform Control Center");
        getContentPane().add(TALabel);
        TALabel.setBounds(80, 34, 340, 40);

        ServerButton.setText("Connect");
        ServerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ServerButton);
        ServerButton.setBounds(280, 350, 130, 23);

        ServerLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ServerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ServerLabel.setText("Server");
        getContentPane().add(ServerLabel);
        ServerLabel.setBounds(310, 334, 70, 20);

        AdministrationToolsButton.setText("Start");
        AdministrationToolsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdministrationToolsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AdministrationToolsButton);
        AdministrationToolsButton.setBounds(140, 350, 80, 23);

        AdministrationToolsLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AdministrationToolsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdministrationToolsLabel.setText("Administration Tools");
        getContentPane().add(AdministrationToolsLabel);
        AdministrationToolsLabel.setBounds(110, 334, 140, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ServerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServerButtonActionPerformed
        ServerButton.setText("Connecting");
        connectToServer();
        ServerButton.setText("Connected");
    }//GEN-LAST:event_ServerButtonActionPerformed

    private void AdministrationToolsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdministrationToolsButtonActionPerformed
        IFD = new AdministrationTools();
        Login frame = new Login();
    }//GEN-LAST:event_AdministrationToolsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlatformControlCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlatformControlCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlatformControlCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlatformControlCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PlatformControlCenter().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdministrationToolsButton;
    private javax.swing.JLabel AdministrationToolsLabel;
    private javax.swing.JButton ServerButton;
    private javax.swing.JLabel ServerLabel;
    private javax.swing.JTextArea TA;
    private javax.swing.JLabel TALabel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
