/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package reu_platform;

//Includes
import java.awt.Component;
import java.awt.GridLayout;
import java.util.LinkedList;
import javax.swing.JTree;
import javax.swing.JTree.*;
import javax.swing.tree.*;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JPanel;
import javax.swing.JCheckBox;
/**
 *
 * @author Bouse
 */
public class Mapping extends javax.swing.JFrame {

    //IDEK here's some stuff.
    private LinkedList<javax.swing.JLabel> userSources = new LinkedList<javax.swing.JLabel>();
    private LinkedList<JPanel> sourcesTabList = new LinkedList<JPanel>();
    private LinkedList<sourceItem> sourceList = new LinkedList<sourceItem>();
    private int totalSources;
    private DefaultTreeModel globalTree;
    private JTree tree;
    private String treeName;
    private DefaultMutableTreeNode parent;
    
    /**
     * Creates new form Mapping
     */
    //Mapping( projectNameTxtField.getText(), tableNameTxtField.getText(),
    //            userSources, userSources.size());
    public Mapping( String name, String titl, 
            LinkedList<javax.swing.JLabel> lst, int len){        
        totalSources = len;
        treeName = new String(titl);
        //Copy linkedlist passed to constructor
        for(int i = 0; i < totalSources; i++)
        { userSources.add( lst.get(i) ); }
        
        //Set the title of the main frame to the Project name
        setTitle( "PLATFORM - " + name);
        
        //Begin the construction of the tree.
        parent = new DefaultMutableTreeNode(treeName);
        DefaultMutableTreeNode category = new DefaultMutableTreeNode(
                "Books for Java Programmers");
        parent.add(category);
        globalTree = new DefaultTreeModel(parent);
        
        initComponents();
                
        //Tabs for the sources of Local Schema
        for(int i = 0; i < totalSources; i++)
        { addSource(lst.get(i).getText(), lst.get(i).getText()); }
    }

    private Mapping() {        
        treeName = new String("Table");
        parent = new DefaultMutableTreeNode(treeName);
        DefaultMutableTreeNode category = new DefaultMutableTreeNode("Books for Java Programmers");
        parent.add(category);
        globalTree = new DefaultTreeModel(parent);
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        globalSchemaPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        newColumnButton = new javax.swing.JButton();
        deleteColumnButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        globalJTree = new JTree(globalTree);
        jToolBar2 = new javax.swing.JToolBar();
        saveToolButton = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        sourcesTabPane = new javax.swing.JTabbedPane(
            javax.swing.JTabbedPane.TOP,
            javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        statusPanel = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        fileItemNew = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        fileItemOpen = new javax.swing.JMenuItem();
        fileItemSave = new javax.swing.JMenuItem();
        fileItemExit = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        addSrcMenuItem = new javax.swing.JMenuItem();
        removeSrcMenuItem = new javax.swing.JMenuItem();
        viewMenu = new javax.swing.JMenu();
        helpMenu = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 400));

        mainPanel.setMinimumSize(new java.awt.Dimension(17, 16));

        globalSchemaPanel.setBackground(new java.awt.Color(255, 255, 255));
        globalSchemaPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Global schema");

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        newColumnButton.setBackground(new java.awt.Color(255, 255, 255));
        newColumnButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bouse\\Documents\\NetBeansProjects\\REU-Platform\\REU_Platform\\src\\reu_platform\\images\\blank01.png")); // NOI18N
        newColumnButton.setToolTipText("new column");
        newColumnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newColumnButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(newColumnButton);

        deleteColumnButton.setBackground(new java.awt.Color(255, 255, 255));
        deleteColumnButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bouse\\Documents\\NetBeansProjects\\REU-Platform\\REU_Platform\\src\\reu_platform\\images\\blank01.png")); // NOI18N
        deleteColumnButton.setToolTipText("delete column");
        deleteColumnButton.setFocusable(false);
        deleteColumnButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteColumnButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        deleteColumnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteColumnButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(deleteColumnButton);

        jScrollPane1.setViewportView(globalJTree);

        javax.swing.GroupLayout globalSchemaPanelLayout = new javax.swing.GroupLayout(globalSchemaPanel);
        globalSchemaPanel.setLayout(globalSchemaPanelLayout);
        globalSchemaPanelLayout.setHorizontalGroup(
            globalSchemaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, globalSchemaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(globalSchemaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, globalSchemaPanelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        globalSchemaPanelLayout.setVerticalGroup(
            globalSchemaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(globalSchemaPanelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        jToolBar2.setRollover(true);

        saveToolButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bouse\\Documents\\NetBeansProjects\\REU-Platform\\REU_Platform\\src\\reu_platform\\images\\blank01.png")); // NOI18N
        saveToolButton.setToolTipText("Save");
        saveToolButton.setFocusable(false);
        saveToolButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saveToolButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(saveToolButton);

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bouse\\Documents\\NetBeansProjects\\REU-Platform\\REU_Platform\\src\\reu_platform\\images\\blank01.png")); // NOI18N
        jButton4.setToolTipText("New Project");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton4);

        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bouse\\Documents\\NetBeansProjects\\REU-Platform\\REU_Platform\\src\\reu_platform\\images\\save.png")); // NOI18N
        jButton5.setToolTipText("Open Project");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton5);

        sourcesTabPane.setForeground(new java.awt.Color(51, 51, 51));
        sourcesTabPane.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        sourcesTabPane.setMaximumSize(new java.awt.Dimension(288, 254));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addComponent(sourcesTabPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(globalSchemaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sourcesTabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addComponent(globalSchemaPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        statusPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        statusLabel.setForeground(new java.awt.Color(51, 51, 51));
        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        statusLabel.setText("Ready");

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statusPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        jMenuBar1.setForeground(new java.awt.Color(51, 51, 51));

        fileMenu.setForeground(new java.awt.Color(51, 51, 51));
        fileMenu.setText("File");

        fileItemNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        fileItemNew.setText("New Project");
        fileItemNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileItemNewActionPerformed(evt);
            }
        });
        fileMenu.add(fileItemNew);
        fileMenu.add(jSeparator1);

        fileItemOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        fileItemOpen.setText("Open Project");
        fileMenu.add(fileItemOpen);

        fileItemSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        fileItemSave.setText("Save");
        fileMenu.add(fileItemSave);

        fileItemExit.setText("Exit");
        fileItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileItemExitActionPerformed(evt);
            }
        });
        fileMenu.add(fileItemExit);

        jMenuBar1.add(fileMenu);

        editMenu.setForeground(new java.awt.Color(51, 51, 51));
        editMenu.setText("Edit");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Undo");
        editMenu.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Redo");
        editMenu.add(jMenuItem2);
        editMenu.add(jSeparator2);

        jMenuItem3.setText("Copy");
        editMenu.add(jMenuItem3);

        jMenuItem4.setText("Cut");
        editMenu.add(jMenuItem4);

        jMenuItem5.setText("Paste");
        editMenu.add(jMenuItem5);

        jMenuBar1.add(editMenu);

        jMenu1.setText("Project");

        addSrcMenuItem.setText("Add Source");
        addSrcMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSrcMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(addSrcMenuItem);

        removeSrcMenuItem.setText("Remove Source");
        removeSrcMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeSrcMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(removeSrcMenuItem);

        jMenuBar1.add(jMenu1);

        viewMenu.setForeground(new java.awt.Color(51, 51, 51));
        viewMenu.setText("View");
        jMenuBar1.add(viewMenu);

        helpMenu.setForeground(new java.awt.Color(51, 51, 51));
        helpMenu.setText("Help");

        jMenuItem6.setText("Help Contents");
        helpMenu.add(jMenuItem6);
        helpMenu.add(jSeparator3);

        jMenuItem7.setText("About");
        helpMenu.add(jMenuItem7);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(statusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileItemNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileItemNewActionPerformed
        // TODO add your handling code here:
          //IFD = new newProject();
        createProject frame = new createProject();
        frame.setVisible(true);
    }//GEN-LAST:event_fileItemNewActionPerformed

    private void fileItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileItemExitActionPerformed
        // TODO add your handling code here:
        //Note: add in a "Are you sure you want to exit?" warning before exiting.
        dispose();
    }//GEN-LAST:event_fileItemExitActionPerformed

    //Pop up dialog prompt, then adds new node to tree.
    private void newColumnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newColumnButtonActionPerformed
        String input = JOptionPane.showInputDialog(null, "New Column Name: ",
					"Add Column", JOptionPane.PLAIN_MESSAGE);    
        DefaultMutableTreeNode child = new DefaultMutableTreeNode(input);
        parent.add(child);
        
        globalTree.reload();
        globalJTree.revalidate();
    }//GEN-LAST:event_newColumnButtonActionPerformed

    private void deleteColumnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteColumnButtonActionPerformed
        DefaultTreeModel model = (DefaultTreeModel)globalJTree.getModel();
        
        //Get the last node selected
        DefaultMutableTreeNode node = (DefaultMutableTreeNode)globalJTree.getLastSelectedPathComponent();
        //Remove node
        model.removeNodeFromParent(node);
        globalTree.reload();
        globalJTree.revalidate();
    }//GEN-LAST:event_deleteColumnButtonActionPerformed

    private void addSrcMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSrcMenuItemActionPerformed
        String input = JOptionPane.showInputDialog(null, "New Source URL: http://",
			"Add Source", JOptionPane.PLAIN_MESSAGE); 
        addSource(input, "http://" + input);
    }//GEN-LAST:event_addSrcMenuItemActionPerformed

    private void removeSrcMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeSrcMenuItemActionPerformed
        sourcesTabPane.remove(sourcesTabPane.getSelectedIndex());
        //Note: add something to remove tab from LinkedList
    }//GEN-LAST:event_removeSrcMenuItemActionPerformed

    private void addCheckButtonActionPerformed(java.awt.event.ActionEvent evt) {    
        //Make a linked list of all the check boxes in the selected tab.
        LinkedList<JCheckBox> checkBoxes = new LinkedList<JCheckBox>();
        for( Component comp : sourceList.get(sourcesTabPane.getSelectedIndex()).checkBoxPanel.getComponents() )
        { if( comp instanceof JCheckBox) checkBoxes.add( (JCheckBox)comp ); }
        
        DefaultTreeModel model = (DefaultTreeModel)globalJTree.getModel();
        DefaultMutableTreeNode node = (DefaultMutableTreeNode)globalJTree.getLastSelectedPathComponent();
        DefaultMutableTreeNode tempChild;
        
        for(int i = 0 ; i < checkBoxes.size(); i++)
        {
            if(checkBoxes.get(i).isSelected())
            {
                tempChild = new 
                        DefaultMutableTreeNode(checkBoxes.get(i).getText());
                node.add(tempChild);   
                model.insertNodeInto(tempChild, node, node.getChildCount()-1);
            }
        }
        //Get the last node selected
        globalTree.reload();
        globalJTree.revalidate();
        
    } 
    
    private void addSource(String srcName, String srcURL)
    {
           sourceList.add( new sourceItem(srcName, srcURL, userSources) );
            
            sourceList.getLast().addCheckButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    addCheckButtonActionPerformed(evt);
                }
            });
                    
            JPanel temp = new JPanel( new GridLayout(0,1) );
            temp.setBackground(new java.awt.Color(255, 255, 255));
            
            //Following code is sort of copied from what was generated by NetBeans
            // and is altered as needed.
            javax.swing.GroupLayout tempLayout = new javax.swing.GroupLayout(temp);
            temp.setBackground(new java.awt.Color(255, 255, 255));
            tempLayout.setHorizontalGroup(
                tempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tempLayout.createSequentialGroup()
                    .addGroup(tempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(tempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tempLayout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(sourceList.getLast().localSchemaLabel))
                            .addGroup(tempLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(sourceList.getLast().theSeperator, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                         .addComponent(sourceList.getLast().checkBoxScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 71, Short.MAX_VALUE))
                 .addGroup(tempLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sourceList.getLast().addCheckButton)
                    .addContainerGap())
            );
            
            tempLayout.setVerticalGroup(
                    tempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tempLayout.createSequentialGroup()
                        .addComponent(sourceList.getLast().localSchemaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        
                        .addComponent(sourceList.getLast().theSeperator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        
                        .addComponent(sourceList.getLast().checkBoxScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        
                        .addComponent(sourceList.getLast().addCheckButton)
                        .addContainerGap())
            );
            
            sourcesTabPane.addTab(sourceList.getLast().getSourceName(), temp);
            sourcesTabPane.revalidate();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new Mapping().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addSrcMenuItem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton deleteColumnButton;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem fileItemExit;
    private javax.swing.JMenuItem fileItemNew;
    private javax.swing.JMenuItem fileItemOpen;
    private javax.swing.JMenuItem fileItemSave;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JTree globalJTree;
    private javax.swing.JPanel globalSchemaPanel;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton newColumnButton;
    private javax.swing.JMenuItem removeSrcMenuItem;
    private javax.swing.JButton saveToolButton;
    private javax.swing.JTabbedPane sourcesTabPane;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JMenu viewMenu;
    // End of variables declaration//GEN-END:variables
}
