package reu_platform;

import java.util.LinkedList;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bouse
 */
public class SchemaMapping extends javax.swing.JFrame {
    //-------------------------------------------------------
    //Declare misc variables
    //-------------------------------------------------------
    private LinkedList<sourceNode> sourcePanels = new LinkedList<sourceNode>();
    
    /**
     * Creates new form NewJFrame
     */
    //Empty constructor. Since we don't want an empty project, forces user to create one.
    public SchemaMapping() {
        //Let's disable this for now.
        //initComponents();
        
        // Force user to create a project, then scrap this one.
        createProject frame = new createProject();
        frame.setVisible(true);
        dispose();
    }
    
    //Filled constructor.
    public SchemaMapping( LinkedList<javax.swing.JLabel> lst ){
        initComponents();
        matchingPanel.setLayout( new java.awt.GridLayout(1,0) );
                
        //for(int i = 0; i < lst.size(); i++)
        //{ sourcePanels.add( lst.get(i) ); }
        //JOptionPane.showMessageDialog( null, "size: " + sourcePanels.size());

        for(int i = 0; i < lst.size(); i++)
        {
            sourcePanels.add( new sourceNode(lst.get(i).getText(), i) );
            matchingPanel.add( sourcePanels.getLast().sourcePanel );
        }

      
        matchingPanel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        matchingScrollPanel = new javax.swing.JScrollPane();
        matchingPanel = new javax.swing.JPanel();
        optionPanel = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SCHEMA MATCHING");

        matchingScrollPanel.setBackground(new java.awt.Color(255, 255, 255));

        matchingPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout matchingPanelLayout = new javax.swing.GroupLayout(matchingPanel);
        matchingPanel.setLayout(matchingPanelLayout);
        matchingPanelLayout.setHorizontalGroup(
            matchingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );
        matchingPanelLayout.setVerticalGroup(
            matchingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );

        matchingScrollPanel.setViewportView(matchingPanel);

        optionPanel.setBackground(new java.awt.Color(255, 255, 255));
        optionPanel.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout optionPanelLayout = new javax.swing.GroupLayout(optionPanel);
        optionPanel.setLayout(optionPanelLayout);
        optionPanelLayout.setHorizontalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        optionPanelLayout.setVerticalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 73, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(optionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(matchingScrollPanel)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addComponent(matchingScrollPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setText("File");
        menuBar.add(jMenu1);

        jMenu2.setText("Edit");
        menuBar.add(jMenu2);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SchemaMapping().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel matchingPanel;
    private javax.swing.JScrollPane matchingScrollPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel optionPanel;
    // End of variables declaration//GEN-END:variables
}
